server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:auth_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    cache: false

app:
  jwt:
    secret: "cGxlYXNlLWNoYW5nZS10aGlzLXNlY3JldC1rZXktcHJvZHVjdGlvbi1yZWFkeS0zMmI="
    expiration-ms: 28800000

  meetings-service:
    base-url: ${MEETINGS_SERVICE_URL:http://localhost:8082}

  internal-api-key: "internal-shared-key"

logging:
  level:
    auth: DEBUG