server:
  port: 8082

spring:
  application:
    name: meetings-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:meetings_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  internal-api-key: "internal-shared-key"

  jwt:
    secret: "cGxlYXNlLWNoYW5nZS10aGlzLXNlY3JldC1rZXktcHJvZHVjdGlvbi1yZWFkeS0zMmI="

  auth-service:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
    internal-api-key: "internal-shared-key"

  export-service:
    base-url: ${EXPORT_SERVICE_URL:http://localhost:8083}
    internal-api-key: "internal-shared-key"

logging:
  level:
    rs.vs.meetings-service: DEBUG