server:
  port: 8082

spring:
  application:
    name: meetings-service

  datasource:
    url: jdbc:mysql://localhost:3306/meetings_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  app:
    jwt:
      secret: "cGxlYXNlLWNoYW5nZS10aGlzLXNlY3JldC1rZXktcHJvZHVjdGlvbi1yZWFkeS0zMmI="
      expiration-ms: 28800000

    auth-service:
      base-url: http://localhost:8081
      internal-api-key: "internal-shared-key"

    export-service:
      base-url: http://localhost:8083
      internal-api-key: "internal-shared-key"

  logging:
    level:
      rs.vs.auth: DEBUG